const ACTIONS = {
    CREATE_NOTE: 'note/create-note',
    TOGGLE_PLAY: 'note/toggle-play',
    UPDATE_SECONDS: 'note/update-seconds',
    UPDATE_MINUTES: 'note/update-minutes',
    UPDATE_HOURS: 'note/update-hours',
    OPEN_OPTIONS: 'note/open-options',
    INCREMENT_HOURS: 'note/increment-hours',
    DECREMENT_HOURS: 'note/decrement-hours',
    INCREMENT_MINUTES: 'note/increment-minutes',
    DECREMENT_MINUTES: 'note/decrement-minutes',
    DELETE_NOTE: 'note/delete-note',
    DELETE_ALL: 'note/delete-all',
    EDIT_TITLE: 'note/edit-title',
    EDIT_TEXT: 'note/edit-text',
    DUPLICATE: 'note/duplicate',
    RESET_TIME: 'note/reset-time',
    LAST_PLAYING: 'note/last-playing',
    UPDATE_CLOCK: 'clock/update-clock',
    INCREMENT_CLOCK_HOURS: 'clock/increment-clock-hours',
    INCREMENT_CLOCK_MINUTES: 'clock/increment-clock-minutes',
    DECREMENT_CLOCK_HOURS: 'clock/decrement-clock-hours',
    DECREMENT_CLOCK_MINUTES: 'clock/decrement-clock-minutes',
    RESET_CLOCK: 'clock/reset-clock',
    RETRIEVE_CLOCK_TIME: 'clock/retrieve-clock-time',
    ADD_CLOCK_TIME_WHEN_DUPLICATE: 'clock/add-clock-time-when-duplicate',
    CHANGE_THEME: 'theme/change-theme'
}

export default ACTIONS;